#   TESTER

server {
    listen 8080;
    root /tmp;

    location /1/ {
    }
}

server {
    listen 8081;
    root /tmp;

    location /2/ {
    }
}

server {
    listen 8082;
    root /tmp;

    location /2/ {
    }
}